apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdfgenz-helm-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pdfgenz-helm
  template:
    metadata:
      labels:
        app: pdfgenz-helm
    spec:
      containers:
        - name: pdfgenz
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
