apiVersion: v1
kind: Service
metadata:
  name: pdfgenz-helm-service
spec:
  selector:
    app: pdfgenz-helm
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
