apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdfgenz-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdfgenz
  template:
    metadata:
      labels:
        app: pdfgenz
    spec:
      containers:
        - name: pdfgenz
          image: pdfgenz-platformops-lab:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
